### ISSUE TITLE
Document for SAS macro

### ISSUE THREAD

**Issue by ynsec37** [yabwon/SAS_PACKAGES#89]
Dear developer,

I wonder if SAS packages may have the ability to automatically create the documentation for SAS, then there is a common way to add comments in SAS program and a tool to generate the documents.

For example, 
- https://github.com/VaccineAndDrugEvaluationCentre/code-diary-sas.
- https://sasjs.io/documentation/

**Comment by yabwon** [comment]
Do you mean something like result of `%helpPackage(packageName,*)` but instead printout in the SAS log but rather to an external file (with "headers" for each code file)? So for example if you write help info text in format of `.md` style you will get it ready.

Bart

**Comment by ynsec37** [comment]
Thank you very much for your reply.

Yes, I wonder how to create the help info in an external file.

I followed the instructions ["Hello World" example tutorial.](https://github.com/yabwon/SAS_PACKAGES/blob/main/SPF/Documentation/HelloWorldPackage.md "Hello World"), after runing `%generatePackage`, there is no related markdown file in the zip file.

For package `baseplus`, there is a help file [baseplus.md](https://github.com/SASPAC/baseplus/blob/main/baseplus.md) in the repository, it seems the information are extracted from the comments between `/*** HELP START ***/` and `/*** HELP END ***/`.

Would you mind share how to create this file? Maybe automatically created by a macro.

**Comment by yabwon** [comment]
I created `md` files by hand form the `%helpPackage(packageName,*)` macro printout. 

I could do that easily because I kept the following rules when writing help notes:
1) I kept markdown format between `/*** HELP START ***/` and `/*** HELP END ***/` blocks. 

2) Additionally for each package component help note I did a "header" line of the following form:
  ```
  ## >>> componentName type: <<< <a name="componentname-type"></a> #######################
  ```
  for example:
  ```
  ## >>> `%getVars()` macro: <<< <a name="getvars-macro"></a> #######################
  ```
  or
  ```
  ## >>> `delDataset()` function: <<< <a name="deldataset-function"></a> #######################
  ```

In the mean time, before I implement "make documentation" functionality you are asking for, assuming you kept to above "rules", the following utility macro (which also uses `%helpPackage()` under the hood) could help you to create a markdown documentation. 

The macro is very plain (like: no checks for `path` existence, etc.) but I tested it on `basePlus` and `macroArray` packages and it generated nice results. If you need any help let me know.

Bart

The utility macro:

```sas
%macro docForPackage(packageName, path);

filename _dcmt_ "&path./%lowcase(&packageName.).md";
filename _dcmt_ list;
filename _temp_ TEMP lrecl=32767;

data _null_;
  file _dcmt_;
  put " ";
  put "# Documentation for `&packageName.` package.";
  put " ";
run;

proc printto LOG=_temp_;
run;
%helpPackage(&packageName.,,packageContentDS=1)
proc printto;
run;

data _null_;
  file _dcmt_ MOD;
  infile _temp_;
  input;
  length line $ 32767;

  if ('NOTE: Help for package' =: _infile_) then prt+1;

  if 1=prt;

  retain cut 7;
  if strip(_infile_)='*** START ***' then cut=3;

  if length(_infile_)>2 then
    do;
      if cut=7 then put "- " @;
      line = substr(_infile_,cut);
      put line;
    end;
  else
    put " ";
run;

data _null_;
  file _dcmt_ MOD;

  if 1=_N_ then
    do;
      put " ";
      put "--- ";
      put "## Content: ";
      put " ";
      put " ";
    end;
  set work.&packageName._content end=_e_;

  put "- [" fileshort type "](#" fileshort +(-1) "-" type +(-1) ")";

  if 1=_E_ then
    do;
      put '- [License](#license)';
      put " ";
      put "--- ";
      put " ";
    end;
run;

filename _temp_ clear;
filename _temp_ TEMP;

proc printto LOG=_temp_;
run;
%helpPackage(&packageName.,*)
proc printto;
run;
filename _temp_ list;

data _null_;
  file _dcmt_ MOD;
  infile _temp_;
  input;
  length line $ 32767;

  if strip(_infile_)='*** START ***' then prt+1;

  if 1=prt;

  if ('NOTE: Help for package' =: _infile_) then stop;

  retain cut 3;
  if length(_infile_)>2 then
    do;
      line = substr(_infile_,cut);
      put line;
    end;
  else
    put " ";
run;

filename _temp_ clear;
filename _temp_ TEMP;

proc printto LOG=_temp_;
run;
%helpPackage(&packageName.,license)
proc printto;
run;
filename _temp_ list;

data _null_;
  file _dcmt_ MOD;
  infile _temp_;
  input;
  length line $ 32767;

  if 1 = _N_ then
    do;
      put " ";
      put "--- ";
      put " ";
      put '## License <a name="license"></a> ######';
      put " ";
    end;

  if _infile_ =: '|';
  retain cut 3;
  if length(_infile_)>2 then
    do;
      line = substr(_infile_,cut);
      put line;
    end;
  else
    put " ";
run;

filename _temp_ clear;
filename _dcmt_ list;
filename _dcmt_ clear;
%mend docForPackage;

/* How to call the macro:

  %docForPackage(MyPackageName,/path/where/tp/store/md/file/)

*/
/* Example:

  %docForPackage(basePlus,R:/)
  %docForPackage(macroArray,R:/)

*/
```

**Comment by ynsec37** [comment]
I try the macro and it work well. Thank you very much for your time and help!

I found that this macro work after the SAS package zip had been created, how about to generate the document from the individual SAS program in the package folder during the developing? 

The macro `%docForPackage(packagePath)` will check the if the folder should be a SAS package folder,  then create the document from the SAS program.

**Comment by yabwon** [comment]
Creating documentation during package generation is my "next step" plan and that's why I wrote: 
_In the mean time, before I implement "make documentation" functionality you are asking for_
:-) :-)

**Comment by yabwon** [comment]
Hey @ynsec37 

I think you will find this [release](https://github.com/yabwon/SAS_PACKAGES/releases/tag/20231210) interesting.

Bart

**Comment by yabwon** [comment]
Case closed. [Release](https://github.com/yabwon/SAS_PACKAGES/releases/tag/20231210)
